services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # Puerto AMQP (para apps)
      - "15672:15672"   # Consola web de administraci√≥n
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - juris_net

networks:
  juris_net:

volumes:
  rabbitmq_data: