services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: janchundia
      POSTGRES_PASSWORD: janchundia
      POSTGRES_DB: juris_tracking
   # ports:
   #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
   # command: -c hba_file=/var/lib/postgresql/data/pg_hba.conf
    networks:
      - proxy_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@juris.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - proxy_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"

      # -------------------------
      # HTTP â†’ HTTPS
      # -------------------------
      - "traefik.http.routers.pgadmin-http.rule=Host(`pgadmin.william-as.com`)"
      - "traefik.http.routers.pgadmin-http.entrypoints=web"
      - "traefik.http.routers.pgadmin-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # -------------------------
      # HTTPS
      # -------------------------
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.william-as.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"

      # -------------------------
      # Servicio interno
      # -------------------------
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

networks:
  proxy_network:
    external: true

volumes:
  postgres_data:
  pgadmin_data:
