services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: janchundia
      POSTGRES_PASSWORD: janchundia
      POSTGRES_DB: juris_tracking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -c hba_file=/var/lib/postgresql/data/pg_hba.conf
    networks:
      - juris_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@juris.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - juris_net
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  juris_net:

volumes:
  postgres_data:
  pgadmin_data: